---
title: Asmith Joseph Project Review 
author: Connor Norris
date: 2025-04-25
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Impact of IPTp Regimen on Pregnancy Outcomes in a Malaria-Endemic Setting

Name of project author(s): Asmith Joseph

Name of project reviewer: Connor Norris

# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component.

Make sure your final document compiles/renders into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)

# Specific project content evaluation

## Background, Context and Motivation

How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

Overall, I think this section is very strong. There are a couple of places where I think you could cite more sources. I think a source would be good in the second paragraph after the sentences starting with "Emerging evidence suggests...", "Additionally, maternal characteristics such as gravidity...", and "Prior research has suggested that previous pregnancy experience." This section is believable and flows well into your study aims, but it would be good to know where you are getting your information here. I also think you explain very well what new information you hope to gain from your analysis. Other than that, make sure the scientific names *Plasmodium* and *Anopholes* in the first paragraph (and elsewhere) are italicized. It may also be good to define what gravidity is.  

### Summary assessment (PICK ONE, DELETE THE OTHERS)

-   strong contextualization and motivation

## Question description

How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?

### Feedback and Comments

See comments above about defining gravidity. Other than that, I think your questions are very well explained.

### Summary assessment

-   question/hypotheses fully clear

## Data description

How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is?

### Feedback and Comments

I think you explain this well.

### Summary assessment

-   source and overall structure of data well explained

## Data wrangling and exploratory analysis

How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

I think what you did was pretty good, though I don't entirely understand some of the things you did. Why did you choose the specific variables you did? You mention converting categorical variables into factors - which variables were those? What does "imputing those with lower levels" mean? I don't think you need to make major changes, just add a little bit more to explain further.

### Summary assessment

-   some weaknesses in wrangling and exploratory component


## Appropriateness of Analysis

Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

In your last methods paragraph, make it very clear which variables are you predicting with your models and which others are the predictors. For example, are you modeling malaria events using adverse health outcomes as predictors, or the other way around? I think your choice to use logistic regression was valid, but I am not entirely sure because it isn't the most clear what you're modeling from your methods.

### Summary assessment

-   defensible but not optimal analysis


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

I like the layout of Table 1, but include the statistics you mention at the beginning of the results section. For Figure 1, I think the choice to use a histogram was good, but I don't like how the bars for each group alternate. I would either do the two groups on separate plots and then facet wrap them together into one figure, or I would overlay the histograms for the two groups on the same plot, whatever would work best for your data. I would also move your figure code around to place the figures nearest to where they are discussed. Also, move the part in your results where you talk about what you did for your machine learning pipeline to the methods.

### Summary assessment

-   results are presented ok, with room for improvement


## Discussion/Conclusions

Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

I think your conclusions were correct and well explained. I also think you explained your limitations well.

### Summary assessment

-   strong, complete and clear discussion

## Further comments

*Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project.*

# Overall project content evaluation

Overall, your prose was very easy to follow, I just think that there are a couple of places where you could add a little bit more to fully explain what you did and why you did it. I think your analysis was well done, and I appreciated the number of models that you fit and how you presented your work to compare their performance.

## Structure

Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

Make sure that you either edit or remove the README files from your repo, they are the same as in the template. Otherwise your directly is well set-up.

### Summary assessment

-   mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)


## Documentation



### Feedback and Comments

I think that your EDA and analysis code is well documented and I can understand what you did. However, I cannot find your processing code, and it looks like there are a lot of redundant files in your processing code folder.

### Summary assessment

-   decently documented with some gaps

## Reproducibility

Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

Other than installing packages, I was able to run all of your code without problem.

### Summary assessment


-   fully reproducible without issues

## Thoroughness

How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

I think you were very thorough with the number of models that you tried, and I think you answered your questions well, even though your models did not give you much to go on.

### Summary assessment

-   strong level of thorougness

## Further comments

Great job overall! I think you only need to make minor changes from this point.
